executable 		= /bin/bash
arguments  		= -i activate.sh venv prompt-machine.py 
log        		= default.log
transfer_input_files 	= activate.sh, prompt-machine.py, prompt.json
output 			= stdout.txt
error			= stderr.txt
should_transfer_files   = IF_NEEDED
request_memory  = 5 GB
request_gpus		= 1
requirements = (TARGET.Machine == "pascal-node03.l3s.intra")
notification    = Always
notify_user     = tobias.kalmbach@stud.uni-hannover.de
queue
