executable              = /bin/bash
arguments               = -i activate.sh venv questionnaire.py send_noti.py
log                     = default.log
transfer_input_files    = activate.sh, questionnaire.py, prompt.json, questions.csv send_noti.py
output                  = stdout.txt
error                   = stderr.txt
should_transfer_files   = IF_NEEDED
request_memory          = 100 GB
request_cpus            = 8
request_gpus            = 2
requirements            = (TARGET.MACHINE == "pascal-node01.l3s.intra") 
stream_output           = True
stream_error            = True
queue
