executable              = /bin/bash
arguments               = -i activate.sh venv prompt-machine.py send_noti.py
log                     = default.log
transfer_input_files    = activate.sh, prompt-machine.py, prompt.json send_noti.py
output                  = stdout.txt
error                   = stderr.txt
should_transfer_files   = IF_NEEDED
request_memory          = 25 GB
request_cpus            = 4
request_gpus            = 2
requirements            = (TARGET.MACHINE == "pascal-node01.l3s.intra") 
stream_output           = True
stream_error            = True
queue
